name: Run Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install numpy pandas scikit-learn wandb opencv-python jupyter
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute main.ipynb --output executed_notebook.ipynb
            